"use client";

import { useMemo, useState } from "react";
import { Calculator, Check, CircuitBoard, Code2, FunctionSquare, Play, RotateCcw } from "lucide-react";

type Lab = "Logic" | "Code" | "Probability" | "Calculus";

export function SimulatorLab() {
  const [lab, setLab] = useState<Lab>("Logic");
  return <div className="simulator-shell"><div className="lab-switcher workspace-panel" role="tablist">{(["Logic", "Code", "Probability", "Calculus"] as Lab[]).map((name) => <button className={lab === name ? "active" : ""} key={name} onClick={() => setLab(name)}>{name === "Logic" ? <CircuitBoard size={16} /> : name === "Code" ? <Code2 size={16} /> : name === "Probability" ? <Calculator size={16} /> : <FunctionSquare size={16} />}{name}</button>)}</div>{lab === "Logic" ? <LogicLab /> : null}{lab === "Code" ? <CodeLab /> : null}{lab === "Probability" ? <ProbabilityLab /> : null}{lab === "Calculus" ? <CalculusLab /> : null}</div>;
}

function LogicLab() { const [a, setA] = useState(false); const [b, setB] = useState(true); const [gate, setGate] = useState("AND"); const output = gate === "AND" ? a && b : gate === "OR" ? a || b : a !== b; return <section className="lab-panel glass-panel"><div className="lab-toolbar"><div><span className="section-kicker">Digital logic</span><h2>Gate playground</h2></div><div>{["AND", "OR", "XOR"].map((item) => <button className={gate === item ? "active" : ""} key={item} onClick={() => setGate(item)}>{item}</button>)}</div></div><div className="logic-stage"><button onClick={() => setA((value) => !value)}><span>Input A</span><strong>{Number(a)}</strong></button><button onClick={() => setB((value) => !value)}><span>Input B</span><strong>{Number(b)}</strong></button><div className="gate-node"><CircuitBoard size={24} /><strong>{gate}</strong></div><div className={output ? "logic-output on" : "logic-output"}><span>Output</span><strong>{Number(output)}</strong></div></div><div className="truth-table"><span>A</span><span>B</span><span>{gate}</span>{[[0,0],[0,1],[1,0],[1,1]].flatMap(([x,y]) => [<b key={`${x}${y}a`}>{x}</b>,<b key={`${x}${y}b`}>{y}</b>,<b key={`${x}${y}o`}>{Number(gate === "AND" ? Boolean(x&&y) : gate === "OR" ? Boolean(x||y) : Boolean(x!==y))}</b>])}</div></section>; }

function CodeLab() { const [ran, setRan] = useState(false); return <section className="lab-panel glass-panel"><div className="lab-toolbar"><div><span className="section-kicker">Structured Programming</span><h2>C++ trace lab</h2></div><button className="run-button" onClick={() => setRan(true)}><Play size={15} /> Run</button></div><div className="code-lab-grid"><pre><code>{`#include <iostream>\nusing namespace std;\n\nint main() {\n  int score = 95;\n  int* ptr = &score;\n  *ptr += 5;\n  cout << score;\n}`}</code></pre><div className="console"><span>Output</span><p>{ran ? "> 100\n\nProcess finished successfully." : "Run the program to inspect its output."}</p></div></div></section>; }

function ProbabilityLab() { const [lambda, setLambda] = useState(3); const bars = useMemo(() => Array.from({length: 8}, (_, k) => { const value = Math.pow(lambda,k) * Math.exp(-lambda) / factorial(k); return Math.round(value * 100); }), [lambda]); return <section className="lab-panel glass-panel"><div className="lab-toolbar"><div><span className="section-kicker">Probability</span><h2>Poisson explorer</h2></div><label>λ = <strong>{lambda}</strong><input type="range" min="1" max="7" value={lambda} onChange={(event) => setLambda(Number(event.target.value))} /></label></div><div className="distribution-chart" aria-label="Poisson probability chart">{bars.map((bar,index) => <div key={index}><span style={{ height: `${Math.max(8, bar * 3)}px` }} /><small>{index}</small></div>)}</div><p className="lab-note"><Check size={15} /> The distribution&apos;s mean and variance are both λ.</p></section>; }

function factorial(value: number): number { return value <= 1 ? 1 : value * factorial(value - 1); }

function CalculusLab() { const [expression, setExpression] = useState("x^2 + 3x"); const [solution, setSolution] = useState(""); return <section className="lab-panel glass-panel"><div className="lab-toolbar"><div><span className="section-kicker">Calculus</span><h2>Step-by-step solver</h2></div><button className="run-button" onClick={() => setSolution(expression === "x^2 + 3x" ? "2x + 3" : "cos(x)")}><Play size={15} /> Differentiate</button></div><label className="math-input"><span>f(x)</span><input value={expression} onChange={(event) => { setExpression(event.target.value); setSolution(""); }} /></label><div className="solution-card"><span>Result</span><strong>{solution || "Enter an expression and solve"}</strong>{solution ? <p>Power rule: d/dx(x²) = 2x · Constant multiple: d/dx(3x) = 3</p> : null}</div><button className="reset-link" onClick={() => { setExpression("x^2 + 3x"); setSolution(""); }}><RotateCcw size={14} /> Reset example</button></section>; }

