export type QuizQuestion = {
  id: string;
  subject: string;
  topic: string;
  prompt: string;
  options: [string, string, string, string];
  correct: number;
  explanation: string;
};

type Row = [
  topic: string,
  prompt: string,
  a: string,
  b: string,
  c: string,
  d: string,
  correct: number,
  explanation: string,
];

const banks: Record<string, Row[]> = {
  "Structured Programming": [
    [
      "Pointers",
      "What does &value evaluate to in C++?",
      "The stored value",
      "The address of value",
      "The size of value",
      "A copied reference",
      1,
      "The address-of operator returns the memory address of its operand.",
    ],
    [
      "Pointers",
      "After int x=4; int* p=&x; *p=9;, what is x?",
      "4",
      "5",
      "9",
      "Undefined",
      2,
      "Dereferencing p writes directly to x.",
    ],
    [
      "Arrays",
      "For int a[5], which is the last valid index?",
      "3",
      "4",
      "5",
      "6",
      1,
      "A five-element array uses indices 0 through 4.",
    ],
    [
      "Functions",
      "Which parameter can modify the caller's integer without a pointer?",
      "int x",
      "const int x",
      "int& x",
      "static int x",
      2,
      "A non-const reference aliases the caller's object.",
    ],
    [
      "Control flow",
      "How many times does for(int i=0;i<4;i++) run?",
      "3",
      "4",
      "5",
      "It never stops",
      1,
      "The values are 0, 1, 2, and 3.",
    ],
    [
      "Types",
      "What is 7 / 2 when both operands are int?",
      "2",
      "3",
      "3.5",
      "4",
      1,
      "Integer division discards the fractional part.",
    ],
    [
      "Scope",
      "A variable declared inside a block is accessible where?",
      "Everywhere",
      "Only in that block and nested blocks",
      "Only in main",
      "Only after the block",
      1,
      "Block scope ends at the closing brace.",
    ],
    [
      "Complexity",
      "What is the time complexity of one pass through n items?",
      "O(1)",
      "O(log n)",
      "O(n)",
      "O(n²)",
      2,
      "Each item is visited once.",
    ],
  ],
  "Computing Fundamentals": [
    [
      "Binary",
      "What is decimal 13 in binary?",
      "1011",
      "1101",
      "1110",
      "1001",
      1,
      "13 = 8 + 4 + 1, so the bits are 1101.",
    ],
    [
      "Data",
      "How many distinct values fit in 8 unsigned bits?",
      "8",
      "128",
      "255",
      "256",
      3,
      "Eight bits encode 2⁸ = 256 patterns.",
    ],
    [
      "CPU",
      "Which CPU unit performs arithmetic and logic?",
      "RAM",
      "ALU",
      "SSD",
      "Bus",
      1,
      "The arithmetic logic unit handles these operations.",
    ],
    [
      "Memory",
      "Which storage is typically volatile?",
      "SSD",
      "ROM",
      "RAM",
      "Flash",
      2,
      "RAM loses its contents when power is removed.",
    ],
    [
      "Networks",
      "Which protocol maps domain names to IP addresses?",
      "HTTP",
      "DNS",
      "FTP",
      "SSH",
      1,
      "DNS resolves names such as example.com to addresses.",
    ],
    [
      "Operating systems",
      "What schedules processes onto the CPU?",
      "Compiler",
      "Kernel",
      "Browser",
      "Database",
      1,
      "Process scheduling is an operating-system kernel responsibility.",
    ],
    [
      "Algorithms",
      "Binary search requires the input to be what?",
      "Random",
      "Encrypted",
      "Sorted",
      "Duplicated",
      2,
      "Ordering lets the algorithm discard half the search space.",
    ],
    [
      "Representation",
      "Which hexadecimal digit equals decimal 15?",
      "E",
      "F",
      "10",
      "A",
      1,
      "Hexadecimal F represents decimal fifteen.",
    ],
  ],
  "Logic Design": [
    [
      "Gates",
      "Which gate is 1 only when its inputs differ?",
      "AND",
      "XOR",
      "NOR",
      "XNOR",
      1,
      "XOR detects unequal binary inputs.",
    ],
    [
      "Gates",
      "A NAND gate is an AND gate followed by what?",
      "A buffer",
      "An inverter",
      "An OR gate",
      "A clock",
      1,
      "NAND is the complement of AND.",
    ],
    [
      "Boolean algebra",
      "Which expression equals A + A·B?",
      "A",
      "B",
      "A·B",
      "A+B",
      0,
      "The absorption law reduces A + AB to A.",
    ],
    [
      "K-maps",
      "Valid Karnaugh-map groups have sizes that are?",
      "Prime numbers",
      "Powers of two",
      "Always four",
      "Odd numbers",
      1,
      "Groups contain 1, 2, 4, 8, ... adjacent cells.",
    ],
    [
      "Flip-flops",
      "Which flip-flop stores one bit with D sampled at a clock edge?",
      "SR latch",
      "D flip-flop",
      "Multiplexer",
      "Decoder",
      1,
      "A D flip-flop captures its D input on the active edge.",
    ],
    [
      "Combinational",
      "A 4-to-1 multiplexer needs how many select bits?",
      "1",
      "2",
      "3",
      "4",
      1,
      "Two bits select one of four inputs.",
    ],
    [
      "Sequential",
      "What distinguishes sequential logic from combinational logic?",
      "More gates",
      "Memory/state",
      "No inputs",
      "Analog voltage",
      1,
      "Sequential circuits depend on stored state as well as inputs.",
    ],
    [
      "Number systems",
      "What is the two's-complement 4-bit representation of -3?",
      "0011",
      "1011",
      "1101",
      "1110",
      2,
      "Invert 0011 and add one to obtain 1101.",
    ],
  ],
  "Calculus & Mathematics": [
    [
      "Derivatives",
      "What is d/dx(x³)?",
      "x²",
      "2x",
      "3x²",
      "3x",
      2,
      "The power rule gives 3x².",
    ],
    [
      "Limits",
      "What is lim x→0 sin(x)/x?",
      "0",
      "1",
      "∞",
      "Undefined",
      1,
      "This fundamental trigonometric limit equals one.",
    ],
    [
      "Integrals",
      "What is ∫2x dx?",
      "x² + C",
      "2x² + C",
      "2 + C",
      "x + C",
      0,
      "Differentiating x² returns 2x.",
    ],
    [
      "Chain rule",
      "What is d/dx sin(x²)?",
      "cos(x²)",
      "2x cos(x²)",
      "2 sin(x)",
      "x cos(x²)",
      1,
      "Differentiate the outer function, then multiply by 2x.",
    ],
    [
      "Optimization",
      "At an interior differentiable local extremum, f'(x) is usually?",
      "1",
      "-1",
      "0",
      "∞",
      2,
      "Fermat's theorem gives a stationary point.",
    ],
    [
      "Series",
      "The geometric series Σrⁿ converges when?",
      "r > 1",
      "|r| < 1",
      "r = 1",
      "r is an integer",
      1,
      "Absolute ratio below one makes terms shrink sufficiently.",
    ],
    [
      "Continuity",
      "A function continuous at a must satisfy what?",
      "f(a)=0",
      "lim f(x)=f(a)",
      "f'(a)=0",
      "f(a)>0",
      1,
      "The limit and function value must exist and agree.",
    ],
    [
      "Derivatives",
      "What is d/dx ln(x)?",
      "ln(x)",
      "x",
      "1/x",
      "eˣ",
      2,
      "The natural logarithm differentiates to the reciprocal.",
    ],
  ],
  "Discrete Mathematics": [
    [
      "Sets",
      "If |A|=3, how many subsets does A have?",
      "3",
      "6",
      "8",
      "9",
      2,
      "A set with n elements has 2ⁿ subsets.",
    ],
    [
      "Logic",
      "The implication p→q is false in which case?",
      "p and q true",
      "p true, q false",
      "p false, q true",
      "Both false",
      1,
      "A true premise cannot imply a false conclusion.",
    ],
    [
      "Graphs",
      "A tree with n vertices has how many edges?",
      "n",
      "n-1",
      "n+1",
      "2n",
      1,
      "Every finite tree has exactly n−1 edges.",
    ],
    [
      "Counting",
      "How many permutations of 4 distinct items exist?",
      "8",
      "12",
      "16",
      "24",
      3,
      "4! = 24.",
    ],
    [
      "Relations",
      "A relation that is reflexive, symmetric, and transitive is?",
      "A function",
      "An equivalence relation",
      "A partial order",
      "A bijection",
      1,
      "Those three properties define equivalence.",
    ],
    [
      "Proof",
      "Mathematical induction proves statements indexed by?",
      "Real numbers",
      "Natural numbers",
      "Matrices",
      "Graphs only",
      1,
      "Induction establishes a base case and successor step.",
    ],
    [
      "Graphs",
      "The sum of all vertex degrees equals?",
      "|E|",
      "2|E|",
      "|V|+|E|",
      "|V|²",
      1,
      "Each edge contributes two degree incidences.",
    ],
    [
      "Combinatorics",
      "What is C(5,2)?",
      "5",
      "10",
      "15",
      "20",
      1,
      "5!/(2!3!) = 10.",
    ],
  ],
  "Physics for CS": [
    [
      "Kinematics",
      "Velocity is the time derivative of what?",
      "Force",
      "Position",
      "Mass",
      "Energy",
      1,
      "Velocity measures the rate of change of position.",
    ],
    [
      "Dynamics",
      "Newton's second law is?",
      "E=mc²",
      "F=ma",
      "V=IR",
      "p=mv²",
      1,
      "Net force equals mass times acceleration.",
    ],
    [
      "Circuits",
      "Ohm's law is?",
      "P=IV",
      "V=IR",
      "Q=CV",
      "F=qE",
      1,
      "Voltage equals current times resistance.",
    ],
    [
      "Energy",
      "The SI unit of energy is the?",
      "Watt",
      "Newton",
      "Joule",
      "Pascal",
      2,
      "Energy is measured in joules.",
    ],
    [
      "Electricity",
      "Two equal positive charges exert what force?",
      "Attractive",
      "Repulsive",
      "Zero",
      "Gravitational only",
      1,
      "Like electric charges repel.",
    ],
    [
      "Waves",
      "Wave speed equals frequency multiplied by?",
      "Amplitude",
      "Wavelength",
      "Period",
      "Energy",
      1,
      "The wave relation is v=fλ.",
    ],
    [
      "Power",
      "Electrical power can be calculated as?",
      "V/I",
      "VI",
      "I/R",
      "VR",
      1,
      "Power transferred is voltage times current.",
    ],
    [
      "Momentum",
      "Linear momentum equals?",
      "ma",
      "mv",
      "mgh",
      "½mv²",
      1,
      "Momentum is mass multiplied by velocity.",
    ],
  ],
  "Differential Equations": [
    [
      "Order",
      "What is the order of y'' + 3y' + y = 0?",
      "First",
      "Second",
      "Third",
      "Zero",
      1,
      "The highest derivative is the second derivative.",
    ],
    [
      "Separable",
      "Which equation is separable?",
      "y'=x+y",
      "y'=xy",
      "y''+y=0",
      "y'=sin(x+y)",
      1,
      "y'=xy rearranges to dy/y = x dx.",
    ],
    [
      "First order",
      "The solution of y'=ky has what form?",
      "y=kx+C",
      "y=Ceᵏˣ",
      "y=Cxᵏ",
      "y=k/x",
      1,
      "Exponential growth and decay solves this equation.",
    ],
    [
      "Linear",
      "A first-order linear equation has standard form?",
      "y²+y=x",
      "y'+P(x)y=Q(x)",
      "yy'=x",
      "y''=Q(x)",
      1,
      "That form admits an integrating factor.",
    ],
    [
      "Initial values",
      "An initial condition primarily determines what?",
      "The equation order",
      "A particular solution",
      "The independent variable",
      "The units",
      1,
      "It selects one member from the solution family.",
    ],
    [
      "Exact",
      "M dx + N dy=0 is exact when?",
      "M=N",
      "Mᵧ=Nₓ",
      "Mₓ=Nᵧ",
      "MN=1",
      1,
      "Equality of the cross partials is the exactness test.",
    ],
    [
      "Equilibria",
      "For y'=f(y), an equilibrium y* satisfies?",
      "f(y*)=1",
      "f(y*)=0",
      "f'(y*)=0 always",
      "y*=x",
      1,
      "At equilibrium the derivative vanishes.",
    ],
    [
      "Homogeneous linear",
      "Superposition applies to which equations?",
      "Nonlinear only",
      "Homogeneous linear",
      "Separable only",
      "Exact only",
      1,
      "Linear homogeneous solution sets are closed under linear combinations.",
    ],
  ],
  "Probability & Statistics": [
    [
      "Probability",
      "For equally likely outcomes, P(A) equals?",
      "|A|/|S|",
      "|S|/|A|",
      "|A|+|S|",
      "1-|S|",
      0,
      "Probability is favorable outcomes divided by all outcomes.",
    ],
    [
      "Conditional",
      "P(A|B) is defined as?",
      "P(A)+P(B)",
      "P(A∩B)/P(B)",
      "P(A)/P(B)",
      "P(B|A)",
      1,
      "Conditioning restricts the sample space to B.",
    ],
    [
      "Poisson",
      "For X~Poisson(λ), the mean and variance are?",
      "0 and 1",
      "λ and λ",
      "λ and λ²",
      "1/λ and λ",
      1,
      "Both parameters equal λ for a Poisson variable.",
    ],
    [
      "Expectation",
      "E[aX+b] equals?",
      "aE[X]+b",
      "E[X]+ab",
      "a+bE[X]",
      "E[X]²",
      0,
      "Expectation is linear.",
    ],
    [
      "Independence",
      "Independent events A and B satisfy?",
      "P(A∩B)=0",
      "P(A∩B)=P(A)P(B)",
      "P(A)=P(B)",
      "A=B",
      1,
      "Product probability characterizes independence.",
    ],
    [
      "Normal",
      "About what percentage lies within one standard deviation of a normal mean?",
      "50%",
      "68%",
      "95%",
      "99.7%",
      1,
      "The empirical rule starts with approximately 68%.",
    ],
    [
      "Variance",
      "Variance measures what?",
      "Center",
      "Spread around the mean",
      "Sample size",
      "Maximum only",
      1,
      "Variance averages squared deviations from the mean.",
    ],
    [
      "Bayes",
      "Bayes' theorem reverses which quantity?",
      "A mean",
      "A conditional probability",
      "A variance",
      "A sample size",
      1,
      "It relates P(A|B) to P(B|A).",
    ],
  ],
};

export const authoredQuestions: QuizQuestion[] = Object.entries(banks).flatMap(
  ([subject, rows]) =>
    rows.map(([topic, prompt, a, b, c, d, correct, explanation], index) => ({
      id: `${subject.toLowerCase().replace(/[^a-z]+/g, "-")}-${index + 1}`,
      subject,
      topic,
      prompt,
      options: [a, b, c, d],
      correct,
      explanation,
    })),
);

export const quizSubjects = Object.keys(banks);

import { buildVariations } from "./question-variations";
export const questionBank = [...authoredQuestions, ...buildVariations()];
